export interface ItemsDatabase {
  tickets: string[];
  containers: string[];
  pets: string[];
  tools: string[];
  resources: string[];
  fish: string[];
  gardening: string[];
  juices: string[];
  subscriptions: string[];
  others: string[];
}

export const ITEMS_DB: ItemsDatabase = {
  tickets: [
    "Car Ticket",
    "Cayo Perico Ticket",
    "Flame and Water Lottery Ticket",
    "Grand Ticket",
    "Lottery Ticket",
    "Rare Lottery Ticket",
    "Resource Miners Ticket",
    "Secret Ticket",
    "Secret Ticket Fragment",
    "regular lottery ticket",
    "Royal Artifacts lottery ticket"
  ],
  containers: [
    "Daily Container",
    "Gardeners Container",
    "Unique Love Container",
    "Desert Scarf Mask Container",
    "Valuable Container",
    "Benefactor Container",
    "Love Container",
    "Resources Container",
    "School Container",
    "Caravan Container",
    "Burglarized House Container",
    "Trezor Container",
    "Container For Bikers 1/2/3/4/5",
    "Container For Branded Shorts",
    "Container For Branded T-Shirts",
    "Sphere Of Influence Container",
    "Container For Drifters 1/2/3",
    "Container For Men 1/2",
    "Container For Racers 1/2/3/4/5",
    "Study Of The Organisation Container",
    "Container For Women 1/2",
    "Container With Wheels 1/2/3",
    "Progen Container",
    "Ocelot Container",
    "Ingrand Container",
    "Old Autumn Gold Container",
    "Old Summer Gold Container",
    "Old Winter Gold Container",
    "Arena Container",
    "Organisation Container",
    "Exclusive Truckers Container",
    "valuable container",
    "biker container",
    "Brand T-shirts 2 container",
    "Brand shorts 2 container",
    "trucker container",
    "racer container",
    "Grand racers container",
    "Maserati container",
    "gardener container",
    "rare love container",
    "regular love container",
    "Renault container",
    "diver container",
    "organization container",
    "wheels 1 container",
    "wheels 2 container",
    "wheels 3 container",
    "daily container",
    "Halloween container",
    "womens gift container of type 1",
    "womens gift container of type 2",
    "males gift container of type 1",
    "males gift container of type 2",
    "blue womens top container of type 4",
    "black womens top container of type 4",
    "Benefactor E500 (W124) container",
    "daily study of the organization container",
    "Captured caravans container",
    "Delivered caravans container",
    "Valentine 2025 container",
    "case of delivered caravans container"
  ],
  pets: [
    "Pet",
    "Pet Border Collie",
    "Pet Cat",
    "Pet Chicken",
    "Pet Christmas Elf",
    "Pet Cute Hippo",
    "Pet Dog",
    "Pet Duckling",
    "Pet Fancy Bear",
    "Pet Food",
    "Pet Ghost",
    "Pet Golden Retriever",
    "Pet Huggy Wuggy",
    "Pet Husky",
    "Pet Kitty Bunny",
    "Pet Lion Cub",
    "Pet Monkey",
    "Pet Panda",
    "Pet Panther",
    "Pet Pig",
    "Pet Poodle",
    "Pet Pug",
    "Pet Puma",
    "Pet Pumpkin Guardian",
    "Pet Rabbit",
    "Pet Rat",
    "Pet Rooster",
    "Pet Rottweiler",
    "Pet Santa Claus",
    "Pet Treat",
    "Pet Voodoo Doll",
    "Pet Westie",
    "Pet X-mas Husky",
    "Pet Mini Robot",
    "Pet Cyberdog",
    "Pet Robobeast",
    "Mr Candy Cane Pet",
    "Futuristic Friend",
    "Cougar Pet"
  ],
  tools: [
    "low quality pickaxe",
    "medium quality pickaxe",
    "high quality pickaxe",
    "max quality pickaxe",
    "advanced quality pickaxe",
    "low quality fishing rod",
    "medium quality fishing rod",
    "high quality fishing rod",
    "max quality fishing rod",
    "advanced quality fishing rod",
    "automatic drill",
    "automatic sawmill",
    "automatic rod",
    "automatic oil well",
    "automatic watering can"
  ],
  resources: [
    "battery",
    "fuel canister",
    "premium fuel canister",
    "charger",
    "solar barrel",
    "gasoline barrel",
    "kerene barrel",
    "fuel for resource extraction",
    "paint can",
    "wire",
    "thread",
    "solar panel",
    "sponges",
    "scrap metal",
    "top quality metal",
    "copper",
    "emerald",
    "ruby",
    "diamond",
    "obsidian",
    "magma stone"
  ],
  fish: [
    "perch",
    "carp",
    "salmon",
    "trout",
    "megalodon",
    "ray",
    "orca",
    "humpback whale"
  ],
  gardening: [
    "cabbage vegetables",
    "pumpkin fruits",
    "mandarin fruits",
    "strawberry fruits",
    "pineapple fruits",
    "cabbage seeds",
    "pumpkin seeds",
    "mandarin seeds",
    "strawberry seeds",
    "pineapple seeds",
    "mushroom seeds"
  ],
  juices: [
    "attack juice",
    "protection juice",
    "endurance juice",
    "riding juice",
    "power juice",
    "immunity juice",
    "juice on becoming an animal",
    "juice for double the payment",
    "fast running juice"
  ],
  subscriptions: [
    "Prime",
    "Prime Platinum"
  ],
  others: [
    "GrandPro BodyCam",
    "Treasure Map",
    "video card",
    "hookah",
    "dice",
    "Leash",
    "SIM card",
    "token",
    "tonic treat",
    "Dirty Statue",
    "Purified Statue",
    "Drawing",
    "letter \"G\"",
    "letter \"R\"",
    "letter \"A\"",
    "letter \"N\"",
    "letter \"D\"",
    "custom license plate",
    "Christmas key",
    "Christmas copper",
    "Christmas timber",
    "Christmas perch",
    "Christmas seed",
    "Christmas lollipop",
    "New years gift",
    "A Little gift",
    "A Big gift",
    "An Opened gift",
    "luminous wheels of type 1",
    "luminous wheels of type 2",
    "luminous wheels of type 3",
    "luminous wheels of type 4",
    "luminous wheels of type 5",
    "luminous wheels of type 6"
  ]
};

export const BUSINESSES_DB = [
  "Ammunition Store", "ATM", "Car wash", "Car sharing", "Chip tuning", "Clothing shop", 
  "Electric station", "Farm", "Flower shop", "Fight club", "Furniture shop", "Gas station", 
  "Grand Elite", "Hair salon", "Jewelry store", "Juice shop", "Luna park", "Parking", 
  "Pet Shop", "State object", "Service station", "Tattoo studio", "Taxi company", 
  "24/7 Store", "Burger shop", "Cowshed", "Freight train", "Plantation", "Oil Well"
];

export const OFFICIAL_PLACES = [
  "Vinewood Hills", "Rockford Hills", "Richman", "Sandy Shores", "Paleto Bay",
  "Postal", "Hospital", "Capitol", "Fire Station", "Auto Fair", "Bahama Mamas Bar",
  "Tequi-la-la Bar", "FIB", "Hotel Spa Bar", "Pacific Bluffs Country Club",
  "Diamond Resort Bar", "Vanilla Unicorn Bar", "Church", "Stock Exchange", "Stadium",
  "Chumash", "Lifeinvader", "Del Perro Pier", "Del Perro Beach", "Cayo Perico Island",
  "Hotel", "Raton Canyon", "School", "SAHP", "Mirror Park", "LSPD"
];

export const UNOFFICIAL_PLACES = [
  "airport", "autosalon", "beach", "beach market", "ghetto", "post office",
  "train station", "yacht", "city"
];

export const REAL_ESTATE_ORDER = [
  "garden", "garage spaces", "warehouses", "helipad", "custom interior", "insurance",
  "swimming pool", "tennis court", "driveway", "backyard", "views", "location"
];

export const ILLEGAL_ITEMS = [
  "ammo", "ammunition", "armor", "vest", "vests", "weapon", "weapons", "firearms", "rifle", "gun", "guns",
  "cocaine", "weed", "drugs", "cannabis", "seeds", "scanners", "radars", "radar", "ems", "mask", "masks",
  "balaclava", "rope", "ropes", "lock pick", "lock picks", "usb", "virus", "troll", "engine block", "smuggling",
  "license plate text", "plate text"
];

export const REJECTION_ONLY_ITEMS = [
  "crowbar", "fabric", "armor skin", "animal skin", "head bag", "air horn", "barricades", "traps",
  "poison darts", "army uniform", "sensor", "sensors", "razor", "razors", "body armor", "body armor plate",
  "first aid kit", "first aid kits", "pill", "pills", "food", "eat"
];

export const BANNED_CONTENT = [
  "grand coin", "grand coins", "battlepass", "hype body armor", "branded armor", "unofficial family",
  "birthday", "sexual", "prostitution", "slaves", "slaves sale", "state org leader", "deputy leader"
];

export const SPELLING_CORRECTIONS: Record<string, string> = {
  "crypto currency": "token",
  "cryptocurrency": "token",
  "crypto": "token",
  "quilty": "quality",
  "lf": "looking for an",
  "platinom": "platinum",
  "casno": "casino",
  "apartemnt": "apartment",
  "appart": "apartment",
  "platinyem": "platinum",
  "panthouse": "penthouse",
  "allience": "alliance",
  "panthuse": "penthouse",
  "lui": "LV",
  "anis": "annis",
  "tubo": "turbo",
  "turb": "turbo",
  "drft": "drift",
  "direct": "drift",
  "tickt": "ticket",
  "tick": "ticket",
  "haus": "house",
  "housae": "house",
  "grage": "garage",
  "exsotic": "exotic",
  "markit": "market",
  "platnum": "platinum",
  "sholder": "shoulder",
  "metel": "metal",
  "mettal": "metal",
  "videocard": "video card",
  "hoka": "hookah",
  "biosparc": "biospark",
  "biosparck": "biospark",
  "biosparke": "biospark",
  "batry": "battery",
  "battries": "battery",
  "battres": "battery",
  "battre": "battery",
  "batteys": "battery",
  "battey": "battery",
  "vinewod": "Vinewood",
  "aprtment": "apartment",
  "apartemen": "apartment",
  "apartmen": "apartment",
  "geto": "ghetto",
  "gheto": "ghetto",
  "swiming": "swimming",
  "luminus": "luminous",
  "drfit": "drift",
  "tickts": "tickets",
  "tckets": "tickets",
  "tikets": "tickets",
  "twith": "with",
  "whith": "with",
  "helipaad": "helipad",
  "helipd": "helipad",
  "gardan": "garden",
  "grden": "garden",
  "costom": "custom",
  "custum": "custom",
  "custome": "custom",
  "inter": "interior",
  "interio": "interior",
  "loking": "looking",
  "lookin": "looking",
  "serch": "search",
  "serching": "searching",
  "girlfrnd": "girlfriend",
  "girlfirnd": "girlfriend",
  "girlfrend": "girlfriend",
  "boyfrnd": "boyfriend",
  "boyfirnd": "boyfriend",
  "boyfrend": "boyfriend",
  "husbnd": "husband",
  "subscr": "subscription",
  "platinum": "platinum",
  "valntine": "valentine"
};

export const OFFICIAL_TEMPLATES = [
  "Join Imad Wanted Family Office (№13724)",
  "Whether you are new or old in the city, if you need money, Office (№13724)",
  "Vanilla Unicorn Bar (GPS №43)",
  "Taxi (GPS №1) near the Casino",
  "Central Mall Weapon Shop (GPS №269)",
  "Elites 24/7 Store No120",
  "Looking to buy affordable and high quality ammunition in bulk? weapon shop (GPS №39) is offering huge discount. Email (lbiiigmatte)",
  "Vyce weapon shop (GPS №39) is offering ammunition at low price all the day, visit now to get amazing deals.Email (lbiiigmatte) or call Ph(12-12-901).",
  "Want buy guns with lowest price? Come to Holdem Ammunation Store (GPS 40) the lowest prices in the city for bulk orders contact via email (ahmad70123)",
  "Visit Holdem Ammunation Store (GPS 40) is Offering 50% discount the lowest prices in the city.",
  "Vio Gun Store (GPS №41) - 50% DISCOUNT We are the CHEAPEST in the city. ALWAYS LOW PRICES guaranteed. Bulk Orders? (Wietru)",
  "Vio Gun Store (GPS №41)  Get 50% discount today. Experience always low prices on all ammo and weapon types in the city. Bulk Orders? (Wietru)",
  "RifleClub (GPS 111) Citys main gun store, lowest ammo prices with 50% discount, bulk orders? Mail (maxdopamine) for extra deals.",
  "RifleClub (GPS 111) Legion Square gun store, lowest ammo prices with a flat 50% discount, bulk orders? Mail (maxdopamine) for extra deals.",
  "Discover Bobbys Ammunition Store (GPS №147), offering quality firearms near SAHP in Paleto Bay.",
  "Visit Bobbys Ammunition Store (GPS №147). Exclusive 50% Off on quality firearms near SAHP in Paleto Bay.",
  "CanikPide Gun Store (GPS No. 148) delivers high-quality firearms at affordable rates citywide. Contact (behzatamir) via mail for bulk orders anytime.",
  "CanikPide Gun Store (GPS No: 148) is always stocked and available 24/7 for bulk orders. You can contact us for bulk orders through mail (behzatamir).",
  "Wong Gun store (GPS No149) is offering highest quality and lowest prices in city! Gear up with us and save big. Mail for bulk orders (Saylex)",
  "Tired of overpaying? Visit Pew Pew GunStore (GPS No:149) for 90% OFF on everything! Bulk deals available on Emails (notsuman).",
  "Gear up at Lue Gun Shop (GPS No150). Top tier firearms and tactical equipment await. Bulk discounts available. Email: (dayzofdeath)",
  "Lock and load for less at Lue Gun Shop (GPS No150)! 50% off all firearms and gear. Dont miss out on this limited time offer. Email: (dayzofdeath)",
  "Siddhu Gun Store (GPS 151) - Locked, loaded, and unbeatable prices. Get top-quality guns at the lowest rates in town. Bulk orders? Mail sidhux123",
  "Siddhu Gun Store (GPS 151) - Limited-time 90% discount on top-quality firearms. Best deals in town. Dont miss out! Bulk orders? Mail sidhux123",
  "Looking for the lowest prices on guns? Visit Most Wanted Store (GPS №152) near Beach Market for unbeatable bulk order! Reach out via email (xkouros)",
  "Dont miss out on incredible discounts up to 90% off at Most Wanted Store (GPS №152)! For guns and ammo, contact us at (xkouros)!",
  "Central Mall Weapon Store (GPS №269)! Premium Weapons and Ammo, Always Stocked for Bulk Orders. Contact Me on 22-20-444 OR Mails (maxuchihax).",
  "Hurry up! Up to 60% OFF on Firearms at Central Mall Weapon Shop (GPS №269)! Limited stock, act fast. Ping Me on 22-20-444 OR Mails (maxuchihax).",
  "Need easy money $132.000 everyday? Office (№24) is for you, offering $10.000 bonus for every task you finish. Contact (d.arsh) via email for bonus!",
  "Do you need extra money? The Office (№24) is for you. Finish simple tasks and earn $132.000 Daily. Offering max bonus Contact via email (d.arsh)",
  "Earn $4.5 Million monthly! Join Al Toman Office (№585) and make $12.000 bonus for every task you finish. Email \"dxdux\" for exclusive bonuses.",
  "Office (№585) is currently offering a $12,000 bonus for each completed task. Interested? Contact (dxdux) via mail for more info!",
  "Struggling with Expenses? Office (№677) got you covered! Get financial support for your daily needs. Reach out to us via email for your daily bonuses!",
  "Say Goodbye to financial stress! Office (№677) provides quick cash for easy tasks. Connect with us through email to claim your daily bonuses.",
  "Easy Money From Me Get 9K For Each Task. We Are Not Alone But We Are The Best OFFICE (N1000) Contact (zekomyth) via email for bonus! or Call 8882288",
  "Get 54k When you complete 6 missions (N1000) Contact (zekomyth) via email for bonus! or Call 8882288",
  "Get rich with the Theo Gucci Office (№1017)! Claim your $5.000 bonus after each task by sending a message to us!",
  "Looking for an effortless way to earn money? Contract with the Theo Gucci Office (№1017) and fill your pockets with cash!",
  "Your millionaire dream begins at Office 1288! Earn 10k per task, 125k a day, 875k every week. Build your future with us. Contact on mails (leveljod)",
  "Build your future at Office 1288! Every task pays 10K. Simple work, big rewards. Dont wait, start today. Contact me on mails (leveljod)",
  "Dont have money? Earn up to $100.000 daily. Contract with Lazy Assassin Office (№1419) and receive $5.000 per task. Contact (imm0rtalop) for bonuses.",
  "Looking for employment opportunities? Join the Lazy Assassin Office (№1419) and earn $5.000 bonus for each task. Email (imm0rtalop) for details.",
  "Empty pockets? Dont worry, earn $124,000 a day with Humans Office (№ 1948). Contact us via email (za3im96) for bonuses!",
  "Quick Money Opportunity! Office No. 1948. Fast, easy earnings. No hard work, just smart work.  email (za3im96) for bonuses!",
  "Become a MILLIONAIRE in the easiest way with Office 2198! $10K bonus per task, $191.800 per day. For more information, contact us by mail. (Saylex)",
  "Earn $191.800 daily at Office (No-2198)! Receive $10K bonuses per task and $50,000 from the referral bonus! Email (Saylex).",
  "Contract with Outlaws Office (№2796). Complete 6 tasks daily and earn cash, enjoy a $30.000 bonus for completing all tasks. Email (bo330) for bonuses!",
  "Outlaws Office (№2796) is waiting for you. Tackle 6 tasks daily, earn money and receive $30.000 bonus for completing all tasks. Contact us at (bo33).",
  "Need quick cash? Get employed at Grand For All Office (№7963) and receive a bonus for each completed task.",
  "Office Grand FOR ALL №7963 offers a bonus of $40.000 after completing all daily tasks.",
  "Do you have dreams? If you say yes, we cant help you. But if you have goals, lets get it done. Contract with Snow Corp. Office (№10364).",
  "Easy tasks, the easiest money. Now with $30.000 bonus. Contract with Snow Corp. Office (№10364). Send email (.networkproblem) for extra bonuses.",
  "Money like Turkish Delight Office 12313! $10,000 bonus per mission, $195.000 daily. For info, mail us. (esjer)",
  "Earn $195,000 daily at Office (No12313)! Get $10,000 per task and various bonuses! mail (esjer) now for this opportunity!",
  "Join Imad Wanted Family Office (№13724)! Today, we are offering bonuses, easy tasks, and extra cash. Then what are you waiting for? Join us now.",
  "Whether you are new or old in the city, if you need money, Office (№13724) offers a 90% profit. We provide bonuses too! Contact us at (mostwanted994)!",
  "Office 14396 gives $10,000 per task! Fast money, no drama. Send email to bylkaanis and start earning today!",
  "Hello! Office 14396 pays $10,000 for each task you complete. Want easy money? Mail bylkaanis and join us now!",
  "Empty pockets? Dont worry, make $100.000 a day by contracting with SAKIB INC Office (№14633). Contact us via email (gamyashiqur) for bonuses!",
  "Tired of not getting paid what was promised by other offices? Dont worry, SakibInc Office (№14633) always offers the highest pay-outs and easy tasks.",
  "Empty pockets? Dont worry, earn $124,000 a day with Lue Office (№15136). Contact us via email (dayzofdeath) for bonuses!",
  "Looking for the highest paying office? Lue Office (№15136) is your best choice! Get a $10,000 bonus per task. Email us at (dayzofdeath).",
  "$11,111 BONUS  $11,111 BONUS  $11,111 BONUS per task Wietru Vio Office (21046) Contact: mail (Wietru)",
  "NO MORE EMPTY POCKETS Your $11.111 task bonus is waiting at Wietru Vio Office (21046) mail (Wietru)",
  "Empty pockets? Join Office 27650 and earn daily with easy tasks. Get up to $10.000 bonus per task. Start now! Contact (bako0804)",
  "Want to earn big money fast? Office 27650 offers $10.000 bonus per task and high daily income. Easy work. Contact via email (bako0804)",
  "Is your girlfriend spending all your money? You do not have to be afraid anymore! The office (№32125) offers money for your daily needs.",
  "Earn $10.000 per task, then blow it all at the casino. Why save when you can gamble hard earned office fortune? Swing by Office №33698 and cash in!",
  "Earn $10.000 per task, Then watch your wife spend it faster than you can make it. Visit Office №33698, At least you can try to win it back!",
  "Nexus Office №41760 sets the gold standard with highest bonus ever. Extra $10.200 bonus per task and $11.000 on weekends. Contact: (argha.bhai).",
  "Step into excellence with Nexus Office №41760. Secure extra $10.200 bonus each task and $11.000 on weekends. Mail: (argha.bhai).",
  "Want to earn easy money by doing simple tasks? Contract with Office No50367 and earn $10.500 bonus on every task. Contact (shivkumar7409) for bonuses.",
  "Office 50367 is Offering $10.500 bonus on every task. Hurry up and Grab this offer, You can earn $135.000 daily. Contact me via email (shivkumar7409).",
  "Office №52942 introduces big profits $64800 daily, Seize this opportunity to enhance your earnings and experience.",
  "Looking to live rich and making great earnings, $64800 daily? Visit the premier office Lex Lyls Office (№52942)",
  "Make riches your reality! Take tasks from Ponch Office №78981! Earn $64.800 daily, $1.9 Million monthly. Prestige meets pay!",
  "Are you new to the city? Want some good cash to begin your journey? Join (Office №78981) and earn $64,800 everyday easily.",
  "$13.000 bonus each task! Join Office 85042 for easy work and earn up to $213.000 per day. Fast rewards and simple tasks. Contact via mails (Creegaint)",
  "$13.000 bonus each task! Big earning opportunity at Office 85042. Makes up to $213.000 daily with simple tasks. Contact via mails (Creegaint)",
  "Hello everyone! Office 85235 gives you $10.000 bonus for each task you do. Hurry up and join us! Contact for bonus at emails guzm4n58.",
  "Earn $10,000 daily task bonus! Join Office (№ 85235) and receive $10,000 for each task, up to $120,000 per day. Email guzm4n58.",
  "Hurry! Store 24/7 №1 (GPS 23) is offering 50% off on everything. Grab your favorite items now. Shop smart, save big!",
  "Why wait? 24/7 Store №1 (GPS 23) is the cheapest in the city. Visit us anytime, 80% discount on Bulk Orders! Contact (creegaint).",
  "Spankys 24/7 №2 (GPS №24) offers cheapest prices and instant delivery on big orders. All day support via mail. Call 99-84-146 or (ganguly07).",
  "Store №2 (GPS №24) Spankys 24/7 runs all day with cheapest rates. Bulk orders get instant delivery. Contact 99-84-146 or (ganguly07).",
  "Beast24/7Store №3 (GPS 25) Always open,Cheapest in city We guarantee low price on all products,open round the clock,for more queries contact-beasto001",
  "Revolutionize your shopping at 24/7 store (GPS №25) deals up to 50% off! Get pickaxes, maps, flowers, tents and more essentials for your daily tasks!",
  "24 Store №26! offers 25% off on bulk orders! For more details or to place an order, call 5111110 or email us at (17uv). Dont miss out on the savings.",
  "Bulk buyers save big at 24 Store №26! Get 25% off on bulk purchases. Reach out at 5111110 or email ( 17uv ) for details and orders.",
  "If you are out of city need groceries, Get up to 60% Discount Today: Visit Shop No. 5 (GPS No 27). Contact: 15-01-505 For Bulk deal in Cheap Price.",
  "Kingdom Grocery Shop No. 5 (GPS No 27), Offering Lowest Prices and Up to 60% Off on Bulk Deals. Contact: 15-01-505 (drakes2030)",
  "Discover amazing prices at Pearl 24/7 Store №28! Always open, always ready for Los Santos!",
  "Pearl 24/7 Store №28 offers -50% discounts in-store! Dont miss -80% bulk deals! Call us: 5550069!",
  "Need a shop near Sandy Shores? We are the cheapest 24/7 of SH side! (GPS №29) We offer 50% sale for all products",
  "Attention Solar Panel Plantation Owners! Maximize your profits with cheapest solar panels! Contact for bulk orders (azuujah)",
  "Hello Los Santos. ZO-ZO 24/7 (Shop No30) Waiting For You On Bulk Orders. 50% To 80% OFF Each Order. Keep Smile With Order Now.",
  "Enjoy a massive 50% discount on store items at 24/7 Store №8 (GPS №30), at Grand Senora Desert. Call 98-54-268 for details.",
  "Mighty Cyber  24/7 Store №.9 (GPS 78) is offering 50% discount for all products.",
  "Welcome to 24/7 Store №9 (GPS 78) is offering  discount for all products. Bulk Orders? Reach out (shodangaming) at mail and get exclusive deals!",
  "Why pay more? Evox Store No.10 (GPS N119) is open 24/7 with up to 90% off lowest prices, day or night!",
  "Evox Imrane 24/7 Store No.10 (GPS N119)  50% off today! Bulk orders? Email us at mails (evox.co)  to save more!",
  "Need something quick? Visit Conco 24/7 Store №11 (GPS №120) for fast access anytime. Always stocked for daily needs. Dial 18-09-842 (montalliago)",
  "Buying in bulk? Visit Conco 24/7 Store №11 (GPS №120) and save more with bulk discounts. Always stocked and ready. Call 18-09-842 (montalliago)",
  "Kings 24/7 Store №121 Get up to 80% off on bulk orders. Quality guaranteed. Open daily with great value on all your essential everyday items.",
  "Kings 24/7 Store №121 Day or night our shelves stay full. From groceries to daily must haves we are always stocked and ready when you walk in.",
  "Come down to BestMoney 24/7 (GPS 123) for the cheapest prices in Paleto Bay! Need bulk orders? We got you covered.",
  "Traveling through Paleto Bay? Stop by Store No13 (GPS123), open 24/7 with travel essentials at great prices. Your one-stop shop on the highway!",
  "Go Grab 24/7, Shop No125, affordable prices with 50% off on all orders! Bulk orders? Enjoy special rates! Contact mails (190uzair)",
  "Go Grab 24/7, Shop No125 always in stock, located in the ghetto, Welcome for bulk orders, Contact us on mails (190uzair)",
  "Do you need items to complete your tasks?  Head to Molotov 24/7 store in Mirror park (GPS №128) for the lowest prices in city.",
  "Lottery tickets, backpacks, solar panels, fishing rods or flowers? Molotov 24/7 (GPS №128) is always stocked and 50%! Contact us for bulk orders!",
  "The holiday season is here! Get your fireworks for New Year! Only at 24/7 Store near the beach! №129",
  "Wifey got your credit card? Her expenses making you broke! No worries The Beach 24/7 Store №129 now offers 50% discount.",
  "Get nonstop cheap rates at Joy Virellii 24/7 Store №18 (GPS №139). Bulk orders welcome. Contact  29-29-290 or masthangaming786 today.",
  "Bulk orders at guaranteed low price. Joy Virellii 24/7 Store №18 (GPS №139). Contact 29-29-290 or masthangaming786 for details now.",
  "Running low on budget? Then look no further! 24/7 Store No19 (GPS 140) is offering 24/7 the best quality goods with 50% off!",
  "Why wait? 24/7 store No19 (GPS 140) is the cheapest in the city. Visit us anytime, 50% discount on Bulk Orders! Contact (only696).",
  "Shopiva 24/7 (No.141) has 50% OFF Bulk orders. We are Open Day and Night providing premium service. Contact .proden to get your stock quickly.",
  "Shopiva 24/7 store (GPS 141) is now offering lowest price guaranteed in the whole city!! Visit now located at the core of Los Santos near Hotel!!",
  "Mall 24/7 Store №270 Save BIG on everything -50% in-store, -80% on bulk orders, LOWEST prices in the heart of the city.",
  "Mall 24/7 Store №270 is at -50% OFF! Make easy money with solar panels and mushroom seeds at the LOWEST prices in the city!",
  "Cheapest Means Best! Come Gas Station NO 3 (GPS No4) inside city FUEL $8!",
  "Gas Station NO 3 (GPS No4) Repair kit $70 Canister $140 For bulk orders (mail devrimcicoban)",
  "We make your gas stop easier, Sahara Royal Gas Station №6 will make sure every drop counts!!",
  "Planning a trip? Need fuel cans and repair kits in case of emergency? Gas Station №6 is here with 50% discount. Every drop counts!!!",
  "Are you run out of fule? Do not worry, just come in Indian oil station №7 (On GPS) is providing high quality fuel in every drop! And visit again.",
  "New in this city? Why are you pay $20 for fuel ? Come to Indian oil gas station №7 (On GPS ). Pay only $8 per liter and save your money.",
  "Do you need high quality fuel for your car? Ron Gas station №8 will provide you excellent fuel for your cars Only $20 per liter. Make your car happy.",
  "Ron Gas station №8 offering 50% discount today. Come get your high quality fuel for your car.",
  "Visit Gas station №6 (GPS №9) will provide $10 per liter, $100 repair kit and $200 canister cheapest fuel in the city.",
  "Gas station №6 (GPS №9) provides cheapest fuel in the city. Provide only $100 repair kit and $200 canister. For bulk orders, contact (nudhory).",
  "Quality fuel and great service at Gas Station 10. Best prices and service in town. Visit Tsunami station today.",
  "Fuel your journey at Gas Station 10. Tsunami provides top-tier service and quality gas every day.",
  "Quality fuel and great service at Gas Station 11. Best prices and service in town. Visit Charon station today.",
  "Fuel your journey at Gas Station 11. Charon provides top-tier service and quality gas every day.",
  "Visit Rich Man gas station (GPS №13) will provide $20 per liter, $350 repair kit and $500 canister cheapest fuel in Rich Man.",
  "Rich Man Gas Station (GPS 13) - 50% off all fuel! Cheapest in town, do not miss out! Bulk orders, contact (badpedro6)",
  "Drive extra miles with Remix Gas station (№14). High quality fuel for a smooth ride, get your gas always for $10, $200 canisters and $100 repair kits.",
  "Remix Gas station №14 The cheapest in the city, buy fuel canister and repair kit in bulk. Contact us by email on (b0n0is)",
  "Running out of fuel on your road trip? Fill up at XR OIL GAS STATION (GPS №15)! Also offers premium fuel, gas canisters, and repair kits.",
  "Looking for the cheapest fuel? XR OIL GAS STATION (GPS №15) offers fuel for just $5 and the lowest prices on gas canisters and repair kits.",
  "Running out of fuel on your road trip? Fill up at KEK OIL GAS STATION (GPS №16)! Also offers premium fuel, gas canisters, and repair kits.",
  "Looking for the cheapest fuel? KEK OIL GAS STATION (GPS №16) offers fuel for just $10 and the lowest prices on gas canisters and repair kits.",
  "Empty tank? No panic! Liff Gas Station (№17) near Doc Highway offers best city prices fuel at $10 per liter, $300 repair kits and $500 canisters.",
  "Liff Gas Station (№17), get the best cheapest fuel in the city with a 50% discount, where superior driving meets smart savings.",
  "Driving near SAHP? Swing by the Cheapest Gas Station (GPS №18) - full stock, fast service, and everything your ride needs!",
  "Running low? Gas Station (GPS NO-18)! Fuel up fast and grab essentials. For bulk deals, Contact us via mails (raveelkhan).",
  "Brody Station $10-L deal! Brody Station №21! Open 24/7, lowest fuel price. Full stock, helipad, free delivery on bulk orders. Contact (bawan3) today!",
  "Save on Fuel! $10-L at Brody Station No21! Open 24/7, lowest price guarantee. Helipad and free delivery for bulk orders. Reach out to (bawan3) now!",
  "Need a quick fuel stop? We got you covered at just $5 per litre! Top-quality fuel, and reliable support. Bulk orders? Contact Immortals Jaadu today!",
  "Running low on fuel ? Stop by Immortals Fuel – fuel at only $5 per litre, plus repair kits $100 and canisters $200 available! DM for bulk orders now.",
  "Welcome to Ron Gas Station №18 (GPS 115). Drive in for quality fuel, special discounts, and bulk order support. Contact (5andeep).",
  "Drive smart with Ron Gas Station №18 (GPS 115). Fuel $15 per liter. Canister $350. Repair Kit $250. Discounts & bulk orders. Contact (5andeep).",
  "Mobil Gas Station No17 (GPS 116). Fuel up fast with trusted service. Bulk fuel & offers available. Contact (amulyt).",
  "Mobil Gas Station No17 (GPS 116). Quick & reliable. Fuel $15/L, Canister $350, Repair Kit $250. Bulk deals available. Contact (amulyt).",
  "Stuck in Paleto Bay? Visit Loves Gas Station №117! Fuel up at just $12/L. Great prices on all essentials!",
  "Loves Fuel №117 – Just $12/L! Save more with bulk deals. Msg (rockyfearless) now to lock in your supply!",
  "Surya Pluxury Gas Station №118 offers $5/L Fuel, $200 Canisters, $100 Repair Kits! Limited time only. Call now: 93-50-311",
  "Tired of paying too much for good quality fuel? Jordan fuel works GPS №118 provides products in cheap and fuel at only $10 per litre inside city!",
  "SHER Gas Station Your One Stop Destination for Quality Fuel and Convenient Services. Visit us at GPS 124!",
  "Gas Station No. 124 offers cheap prices in the city. For more details, contact me in email yassir001.",
  "Listen up riders! Need quality fuel? Visit Gas Station №21 (GPS №127) fuel up, grab kits, and get back in motion. PH: 22-64-883.",
  "Running low? Dont push that luck. Visit Gas station №21 (GPS №127) for high quality fuel and canisters. Contact: 22-64-883.",
  "Renegades Gas Station, in the middle of the map, GPS №136 offers the LOWEST Price Per Liter, just $7. For bulk orders, Contact HELLBRAZER or VAILLYRP.",
  "Limited time discounts at Gas Station GPS №136 $7 Per Liter, cheap Repair Kits and Canisters! Do not miss out! Contact: (HELLBRAZER or VAILLYRP)",
  "OILARC Gas Station No23 (GPS 137) Near Hospital of Sandy Shores, Providing 50% discount on Fuel and everything. For bulk orders mails (rupoj).",
  "Running low on fuel near Sandy shoes? Visit OILARC Gas station No23 (GPS 137) Providing fuel at $5 Per litre. For bulk orders mails (rupoj).",
  "With our parking number 1 (GPS №51)  we are offering 1000 per place! come take your car and dont miss this opportunity.",
  "Party lovers unite! Go to Parking №2 - where events shine, parties pop and the beach view beats your dance moves.",
  "Car fans unite! Go to Parking №2 - where engines roar, lights glow and every ride turns heads at the hottest beach meet.",
  "Are you afraid of scratching your vehicles? Do not be afraid, use Ekip Parking Lot (GPS №53)",
  "Unique Comfort and Security Only Book at EKIP Parking (GPS№53), Guarantee Luxury Care for Your Vehicle!",
  "Are you afraid of scratching your vehicles? Dont be afraid, use Ekip Parking Lot (GPS №54)",
  "Unique Comfort and Security Only Book at EKIP Parking (GPS №54), Guarantee Luxury Care for Your Vehicle!",
  "Take your car from the garage, drive and park in luxury. Parking №5 (GPS №55) VIP style and security for $1.000",
  "Dont look for a parking space in the crowd! Your car is safe with Parking №5 (GPS №55). Regular spaces and pocket friendly prices await you.",
  "Tired of paying $15,000 to rent? Park 6 (GPS №56) is located under Vinewood. Only $1,000 to park your car for the whole day.",
  "Are you looking for safe, hygienic and economical parking? (No56) You are in the right place!",
  "Looking for parking lots? Parking (GPS №57) is now offering 90% off and is only $1.000 per day.",
  "Dont forget to visit us at Eileen Parking (GPS №57). Customer satisfaction is our top priority.",
  "Parking №8 (GPS №58) Near City mall in the middle of the city is offering the cheapest rates in the city. Book your space today for only $1.000!",
  "Parking №8 (GPS №58) Near City mall middle of the city is the best and safest place to park in city. Visit us today for cheap parking!",
  "Secure the cheapest Parking №10 (GPS №79) in the city Center for just $1.000 each day. Prime location near beach market, affordable rates.",
  "Looking for a parking? Limited offer, dont miss out just 1000$ at Playboys Parking! (GPS №79)",
  "Dont look for a parking space in the crowd! Your car is safe with Parking №11 (GPS №80). Regular spaces and pocket friendly prices await you.",
  "Unique Comfort and Security Only  Book at EKIP Parking (GPS №80), Guarantee Luxury Care for Your Vehicle!",
  "Are you bored of paying $15.000 for renting? Parking 12 (GPS №81) is located in the center of the city Just $1.000 to have your car parked all day.",
  "Tired of your car not being where you left it? Use Parking 12 (GPS 81) For a very cheap price!",
  "Some security can only be found at Remix Parking Lot Guarding, cleaning and security. 50% cash back when dealing with us Contact me via (zekomyth)",
  "Unique Comfort and Security Only  Book at Remix Parking (GPS №82), Guarantee Luxury Care for Your Vehicle! 50% cash back Contact me via (zekomyth)",
  "Are you afraid of scratching your vehicles? Dont be afraid, use Ekip Parking Lot (GPS №83).",
  "Unique Comfort and Security Only Book at EKIP Parking (GPS №83), Guarantee Luxury Care for Your Vehicle!",
  "Are you bored of paying $15.000 for renting? Parking 15 (GPS №84) is located in the middle of the beach. Just $5.000 to have your car parked all day.",
  "Are you bored of paying $15.000 for renting? Parking 15 (GPS №84) is located in the middle of the beach. Just $1.000 to have your car parked all day.",
  "Parking space №16 (GPS №85) attached to the Train Station Apartment, is offering the cheapest rates in the city. Book your space today for only $1.000",
  "Parking №16 (GPS №85) attached to the Train Station Apartment is the best and safest place to park in city. Visit us today for cheap parking!",
  "Secure the cheapest Parking №17 (GPS №101) in the city Center for just $1.000 each day. Prime location, affordable rates. Reserve your spot now!",
  "Homeless? Secure parking (GPS №101) for your car! Reserve now, park with ease. The citys cheapest at $1.000 a day!",
  "Tired of circling the block in search of parking? Welcome to Parking (GPS №135), your hassle solution for suitable and secure parking, at $1.000 only!",
  "Rockford Parking №18. (GPS №135). Just $1.000 per day near Hotel and LI. Offer for completing jobs task! Just contact me. (kosa.123).",
  "Seeking Power, Unity and Legacy? Uchiha Clan provides Great Vibes, Strong Bonds and Endless Fun. Join us at House №55 or Contact (maxuchihax).",
  "Looking for Strength, Loyalty and Family? Uchiha Clan offers Unity, Fun and True Respect. Join us at House №55 or Contact (maxuchihax).",
  "Join Kingdom family at House №258 Provides Best bonus, supercars, helis and supportive staff. To join call 77-66-888 or mail king.kaushik",
  "Kingdom family is open at House №258. Providing high bonus, best cars, helis and helpful team. Ph. 77-66-888 or mails king.kaushik",
  "The Deluca Cartel is looking for skilled individuals, A family built on trust, unity and respect. Join Deluca Cartel at house №536 today!",
  "Looking for a strong family with loyal people and skilled individuals? Join Deluca Cartel at house №536 today, become a part of something powerful!",
  "Upgrade your style this week at Clothing Shop n1 (GPS 31) ! Special offers, lowest prices, and exclusive outfits. Don t miss out!",
  "Upgrade your style at Clothing Shop n1 (GPS 31) ! Special prices, exclusive outfits. For bulk orders Contact via email (topgs1)",
  "Shop the latest styles at great prices. Trendy clothes for every occasion. Visit us today and refresh your wardrobe with 50% off Clothing Shop (No.32)",
  "Clothing store 2 (No.32) is offering 50% discount and more than 50% discount for bulk order message me in email (rupoj) or contact 1181112",
  "Best style, best prices at TrendZone (Shop 3 on map). Look great for less! PH 6326759 MAILS nzoo.x.",
  "Upgrade your wardrobe at Fashion Point (Shop 3 on map). Hot styles, low prices! PH 6326759 MAILS nzoo.x.",
  "Clothing Shop №4 at (GPS №74) provides quality clothes at wholesale rates. Get 50% off and more on bulk orders. Ph. 66-60-333. Mails (abirsikder70)",
  "Clothing Shop №4 at (GPS №74) provides clothes at wholesale rates. Enjoy 50% off sales, best for bulk orders. Ph.66-60-333 or mail (abirsikder70)",
  "Come to our Store No5 (GPS 75) to dress stylishly and affordably. For bulk purchases, contact me via email at (halilbeyy45).",
  "For stylish and affordable clothes, visit No5 (GPS 75) and contact us via email (halilbeyy45)",
  "Come to our Store No7 (GPS 122) to dress stylishly and affordably. For bulk purchases, contact me via email at (halilbeyy45).",
  "For stylish and affordable clothes, visit No7 (GPS 122) and contact us via email (halilbeyy45).",
  "Are You Looking For Bulk Clothes For Families? Come Contact Clothing Store 6 ( GPS 126), At Cheapest Price You Cant Imagine!",
  "You Want Best Quality Clothes, With Cheapest Price You Cant Imagine? Come Clothing Shop 6 (GPS 126), And Get Maximum Discount And Cashback!",
  "Getting bored with old outfits? Visit Troy Collection Shop №142 for unique and branded clothing at 70% discount!",
  "If boys are not looking at you! Visit Troy Collection Shop №142 at 70% discount for all the clothing.",
  "Everyone deserves a great look! Visit to Veneta Clothing (№143) and get yourself a great outfit at a 50% discount! We are located at near Postal.",
  "Veneta Clothing Store (№143) has the lowest prices, the latest, high quality clothes and is always fully stocked! for family bulk orders contact us.",
  "Need clothes for your family at the best price? Shop at Moonlight Clothing Shop (GPS №144) for unbeatable deals! Contact (lkaan5) now!",
  "Clothing store №144 has lowest price at 50% Discount for high quality clothes and is always fully stocked! Contact (lkaan5) now!",
  "Upgrade your style at LAAALO Clothing Shop No12 (GPS 145) ! Special offers and exclusive outfits. For bulk orders, contact me via email at (xlaaalo).",
  "LIMITED TIME! Clothing Shop №12 (GPS 145) 50% OFF EVERYTHING - best deals in the city! Pull up now before its gone! For Bulk orders contact (xlaaalo)",
  "Clothing Shop GPS №146 (Shop No.13 on map). Perfect for families and daily wear. Bulk orders available. PH: 98-54-268 or email (sachin2309).",
  "Hurry up! 50% discount at Clothing Shop (№.13) best styles at great prices. Visit now before the offer ends. Contact 98-54-268 or email (sachin2309).",
  "Los Santos Clothing Store (GPS №271) is now offering 50% Off in all products! Located inside the biggest mall in the city.",
  "Dont forget once again the crazy deals of Los Santos Clothing Store (GPS №271). Now offering 50% Off in all products!",
  "Level up your style for less. Clothing Shop №2 (GPS №275) offers top looks low prices and new drops daily. Visit us today or call (26-96-969).",
  "Fresh styles low prices daily. Visit us today for best deals at Clothing Shop №2 (GPS №275) contact me via mails at (azarel.11) or call (26-96-969)."
];

export const PRESET_BUTTONS_DEFAULT = [
  { label: "Sell: 10 Grand Tickets", raw: "selling 10 rp tickets for 350k each", count: 12 },
  { label: "Buy: Prime Platinum", raw: "buying prime platinum 30 days", count: 11 },
  { label: "Auto: Sandking XL", raw: "selling fully upgraded sandking xl", count: 10 },
  { label: "Buy: Truffade Chiron", raw: "buying truffade chiron", count: 9 },
  { label: "Buy: Cage Pet", raw: "buying pet", count: 8 },
  { label: "Sell: Cage Pet", raw: "selling pet 600k", count: 7 },
  { label: "Sell: House №1406", raw: "selling house 1406", count: 6 },
  { label: "Dating: Girlfriend", raw: "looking for girlfriend", count: 5 },
  { label: "Sell: SIM Card", raw: "selling sim card 1111113", count: 4 },
  { label: "Buy: SIM Card", raw: "buying sim card 7777777", count: 3 },
  { label: "Sell: Charger", raw: "selling charger", count: 2 },
  { label: "Sell: 10 Salmon", raw: "selling 10 salmon", count: 1 }
];
