export interface ItemsDatabase {
  tickets: string[];
  containers: string[];
  pets: string[];
  tools: string[];
  resources: string[];
  fish: string[];
  gardening: string[];
  juices: string[];
  subscriptions: string[];
  others: string[];
}

export const ITEMS_DB: ItemsDatabase = {
  tickets: [
    "Car Ticket",
    "Cayo Perico Ticket",
    "Flame and Water Lottery Ticket",
    "Grand Ticket",
    "Lottery Ticket",
    "Rare Lottery Ticket",
    "Resource Miners Ticket",
    "Secret Ticket",
    "Secret Ticket Fragment",
    "regular lottery ticket",
    "Royal Artifacts lottery ticket"
  ],
  containers: [
    "Daily Container",
    "Gardeners Container",
    "Unique Love Container",
    "Desert Scarf Mask Container",
    "Valuable Container",
    "Benefactor Container",
    "Love Container",
    "Resources Container",
    "School Container",
    "Caravan Container",
    "Burglarized House Container",
    "Trezor Container",
    "Container For Bikers 1/2/3/4/5",
    "Container For Branded Shorts",
    "Container For Branded T-Shirts",
    "Sphere Of Influence Container",
    "Container For Drifters 1/2/3",
    "Container For Men 1/2",
    "Container For Racers 1/2/3/4/5",
    "Study Of The Organisation Container",
    "Container For Women 1/2",
    "Container With Wheels 1/2/3",
    "Progen Container",
    "Ocelot Container",
    "Ingrand Container",
    "Old Autumn Gold Container",
    "Old Summer Gold Container",
    "Old Winter Gold Container",
    "Arena Container",
    "Organisation Container",
    "Exclusive Truckers Container",
    "valuable container",
    "biker container",
    "Brand T-shirts 2 container",
    "Brand shorts 2 container",
    "trucker container",
    "racer container",
    "Grand racers container",
    "Maserati container",
    "gardener container",
    "rare love container",
    "regular love container",
    "Renault container",
    "diver container",
    "organization container",
    "wheels 1 container",
    "wheels 2 container",
    "wheels 3 container",
    "daily container",
    "Halloween container",
    "womens gift container of type 1",
    "womens gift container of type 2",
    "males gift container of type 1",
    "males gift container of type 2",
    "blue womens top container of type 4",
    "black womens top container of type 4",
    "Benefactor E500 (W124) container",
    "daily study of the organization container",
    "Captured caravans container",
    "Delivered caravans container",
    "Valentine 2025 container",
    "case of delivered caravans container"
  ],
  pets: [
    "Pet",
    "Pet Border Collie",
    "Pet Cat",
    "Pet Chicken",
    "Pet Christmas Elf",
    "Pet Cute Hippo",
    "Pet Dog",
    "Pet Duckling",
    "Pet Fancy Bear",
    "Pet Food",
    "Pet Ghost",
    "Pet Golden Retriever",
    "Pet Huggy Wuggy",
    "Pet Husky",
    "Pet Kitty Bunny",
    "Pet Lion Cub",
    "Pet Monkey",
    "Pet Panda",
    "Pet Panther",
    "Pet Pig",
    "Pet Poodle",
    "Pet Pug",
    "Pet Puma",
    "Pet Pumpkin Guardian",
    "Pet Rabbit",
    "Pet Rat",
    "Pet Rooster",
    "Pet Rottweiler",
    "Pet Santa Claus",
    "Pet Treat",
    "Pet Voodoo Doll",
    "Pet Westie",
    "Pet X-mas Husky",
    "Pet Mini Robot",
    "Pet Cyberdog",
    "Pet Robobeast",
    "Mr Candy Cane Pet",
    "Futuristic Friend",
    "Cougar Pet"
  ],
  tools: [
    "low quality pickaxe",
    "medium quality pickaxe",
    "high quality pickaxe",
    "max quality pickaxe",
    "advanced quality pickaxe",
    "low quality fishing rod",
    "medium quality fishing rod",
    "high quality fishing rod",
    "max quality fishing rod",
    "advanced quality fishing rod",
    "automatic drill",
    "automatic sawmill",
    "automatic rod",
    "automatic oil well",
    "automatic watering can"
  ],
  resources: [
    "battery",
    "fuel canister",
    "premium fuel canister",
    "charger",
    "solar barrel",
    "gasoline barrel",
    "kerene barrel",
    "fuel for resource extraction",
    "paint can",
    "wire",
    "thread",
    "solar panel",
    "sponges",
    "scrap metal",
    "top quality metal",
    "copper",
    "emerald",
    "ruby",
    "diamond",
    "obsidian",
    "magma stone"
  ],
  fish: [
    "perch",
    "carp",
    "salmon",
    "trout",
    "megalodon",
    "ray",
    "orca",
    "humpback whale"
  ],
  gardening: [
    "cabbage vegetables",
    "pumpkin fruits",
    "mandarin fruits",
    "strawberry fruits",
    "pineapple fruits",
    "cabbage seeds",
    "pumpkin seeds",
    "mandarin seeds",
    "strawberry seeds",
    "pineapple seeds",
    "mushroom seeds"
  ],
  juices: [
    "attack juice",
    "protection juice",
    "endurance juice",
    "riding juice",
    "power juice",
    "immunity juice",
    "juice on becoming an animal",
    "juice for double the payment",
    "fast running juice"
  ],
  subscriptions: [
    "Prime",
    "Prime Platinum"
  ],
  others: [
    "GrandPro BodyCam",
    "Treasure Map",
    "video card",
    "hookah",
    "dice",
    "Leash",
    "SIM card",
    "token",
    "tonic treat",
    "Dirty Statue",
    "Purified Statue",
    "Drawing",
    "letter \"G\"",
    "letter \"R\"",
    "letter \"A\"",
    "letter \"N\"",
    "letter \"D\"",
    "custom license plate",
    "Christmas key",
    "Christmas copper",
    "Christmas timber",
    "Christmas perch",
    "Christmas seed",
    "Christmas lollipop",
    "New years gift",
    "A Little gift",
    "A Big gift",
    "An Opened gift",
    "luminous wheels of type 1",
    "luminous wheels of type 2",
    "luminous wheels of type 3",
    "luminous wheels of type 4",
    "luminous wheels of type 5",
    "luminous wheels of type 6"
  ]
};

export const BUSINESSES_DB = [
  "Ammunition Store", "ATM", "Car wash", "Car sharing", "Chip tuning", "Clothing shop", 
  "Electric station", "Farm", "Flower shop", "Fight club", "Furniture shop", "Gas station", 
  "Grand Elite", "Hair salon", "Jewelry store", "Juice shop", "Luna park", "Parking", 
  "Pet Shop", "State object", "Service station", "Tattoo studio", "Taxi company", 
  "24/7 Store", "Burger shop", "Cowshed", "Freight train", "Plantation", "Oil Well"
];

export const OFFICIAL_PLACES = [
  "Vinewood Hills", "Rockford Hills", "Richman", "Sandy Shores", "Paleto Bay",
  "Postal", "Hospital", "Capitol", "Fire Station", "Auto Fair", "Bahama Mamas Bar",
  "Tequi-la-la Bar", "FIB", "Hotel Spa Bar", "Pacific Bluffs Country Club",
  "Diamond Resort Bar", "Vanilla Unicorn Bar", "Church", "Stock Exchange", "Stadium",
  "Chumash", "Lifeinvader", "Del Perro Pier", "Del Perro Beach", "Cayo Perico Island",
  "Hotel", "Raton Canyon", "School", "SAHP", "Mirror Park", "LSPD"
];

export const UNOFFICIAL_PLACES = [
  "airport", "autosalon", "beach", "beach market", "ghetto", "post office",
  "train station", "yacht", "city"
];

export const REAL_ESTATE_ORDER = [
  "garden", "garage spaces", "warehouses", "helipad", "custom interior", "insurance",
  "swimming pool", "tennis court", "driveway", "backyard", "views", "location"
];

export const ILLEGAL_ITEMS = [
  "ammo", "ammunition", "armor", "vest", "vests", "weapon", "weapons", "firearms", "rifle", "gun", "guns",
  "cocaine", "weed", "drugs", "cannabis", "seeds", "scanners", "radars", "radar", "ems", "mask", "masks",
  "balaclava", "rope", "ropes", "lock pick", "lock picks", "usb", "virus", "troll", "engine block", "smuggling",
  "license plate text", "plate text"
];

export const REJECTION_ONLY_ITEMS = [
  "crowbar", "fabric", "armor skin", "animal skin", "head bag", "air horn", "barricades", "traps",
  "poison darts", "army uniform", "sensor", "sensors", "razor", "razors", "body armor", "body armor plate",
  "first aid kit", "first aid kits", "pill", "pills", "food", "eat"
];

export const BANNED_CONTENT = [
  "grand coin", "grand coins", "battlepass", "hype body armor", "branded armor", "unofficial family",
  "birthday", "sexual", "prostitution", "slaves", "slaves sale", "state org leader", "deputy leader"
];

export const SPELLING_CORRECTIONS: Record<string, string> = {
  "crypto currency": "token",
  "cryptocurrency": "token",
  "crypto": "token",
  "quilty": "quality",
  "lf": "looking for an",
  "platinom": "platinum",
  "casno": "casino",
  "apartemnt": "apartment",
  "appart": "apartment",
  "platinyem": "platinum",
  "panthouse": "penthouse",
  "allience": "alliance",
  "panthuse": "penthouse",
  "lui": "LV",
  "anis": "annis",
  "tubo": "turbo",
  "turb": "turbo",
  "drft": "drift",
  "direct": "drift",
  "tickt": "ticket",
  "tick": "ticket",
  "haus": "house",
  "housae": "house",
  "grage": "garage",
  "exsotic": "exotic",
  "markit": "market",
  "platnum": "platinum",
  "sholder": "shoulder",
  "metel": "metal",
  "mettal": "metal",
  "videocard": "video card",
  "hoka": "hookah",
  "biosparc": "biospark",
  "biosparck": "biospark",
  "biosparke": "biospark",
  "batry": "battery",
  "battries": "battery",
  "battres": "battery",
  "battre": "battery",
  "batteys": "battery",
  "battey": "battery",
  "vinewod": "Vinewood",
  "aprtment": "apartment",
  "apartemen": "apartment",
  "apartmen": "apartment",
  "geto": "ghetto",
  "gheto": "ghetto",
  "swiming": "swimming",
  "luminus": "luminous",
  "drfit": "drift",
  "tickts": "tickets",
  "tckets": "tickets",
  "tikets": "tickets",
  "twith": "with",
  "whith": "with",
  "helipaad": "helipad",
  "helipd": "helipad",
  "gardan": "garden",
  "grden": "garden",
  "costom": "custom",
  "custum": "custom",
  "custome": "custom",
  "inter": "interior",
  "interio": "interior",
  "loking": "looking",
  "lookin": "looking",
  "serch": "search",
  "serching": "searching",
  "girlfrnd": "girlfriend",
  "girlfirnd": "girlfriend",
  "girlfrend": "girlfriend",
  "boyfrnd": "boyfriend",
  "boyfirnd": "boyfriend",
  "boyfrend": "boyfriend",
  "husbnd": "husband",
  "subscr": "subscription",
  "platinum": "platinum",
  "valntine": "valentine"
};

export const PRESET_BUTTONS_DEFAULT = [
  { label: "Sell: 10 Grand Tickets", raw: "selling 10 rp tickets for 350k each", count: 12 },
  { label: "Buy: Prime Platinum", raw: "buying prime platinum 30 days", count: 11 },
  { label: "Auto: Sandking XL", raw: "selling fully upgraded sandking xl", count: 10 },
  { label: "Buy: Truffade Chiron", raw: "buying truffade chiron", count: 9 },
  { label: "Buy: Cage Pet", raw: "buying pet", count: 8 },
  { label: "Sell: Cage Pet", raw: "selling pet 600k", count: 7 },
  { label: "Sell: House №1406", raw: "selling house 1406", count: 6 },
  { label: "Dating: Girlfriend", raw: "looking for girlfriend", count: 5 },
  { label: "Sell: SIM Card", raw: "selling sim card 1111113", count: 4 },
  { label: "Buy: SIM Card", raw: "buying sim card 7777777", count: 3 },
  { label: "Sell: Charger", raw: "selling charger", count: 2 },
  { label: "Sell: 10 Salmon", raw: "selling 10 salmon", count: 1 }
];
