export interface VehicleDatabase {
  helicopters: string[];
  boats: string[];
  planes: string[];
  motorcycles: string[];
  not_sellable_cars: string[];
  sellable_cars: string[];
}

export const VEHICLE_DB: VehicleDatabase = {
  helicopters: [
    "Buzzard",
    "Frogger",
    "Maverick",
    "Sparrow",
    "SuperVolito Carbon",
    "Swift Deluxe",
    "Volatus"
  ],
  boats: [
    "Dinghy",
    "Dinghy (2-Seater)",
    "Dinghy (Yacht)",
    "Jetmax",
    "Marquis",
    "SeaShark",
    "Speeder",
    "Squalo",
    "Suntrap",
    "Toro",
    "Tropic"
  ],
  planes: [
    "Alpha-Z1",
    "Cuban 800",
    "Dodo",
    "Duster",
    "Howard NX-25",
    "Luxor",
    "Luxor Deluxe",
    "Malard",
    "Mammatus",
    "Microlight",
    "Nimbus",
    "P-45 Nokota",
    "V-65 Molotok",
    "Velum"
  ],
  motorcycles: [
    "Akuma",
    "Bagger",
    "Carbon RS",
    "Daemon",
    "Enduro",
    "Faggio",
    "Gargoyle",
    "Hakuchou",
    "Innovation",
    "Lectro",
    "Manchez",
    "Nemesis",
    "PCJ-600",
    "Rat Bike",
    "Sanchez",
    "Thrust",
    "Vader",
    "Whippet Race Bike",
    "Zombie Chopper",
    "Apocalypse Deathbike",
    "Bati 801",
    "Chimera",
    "Defiler",
    "Esskey",
    "FCR 1000",
    "Hakuchou Drag",
    "Nightblade",
    "Ruffian",
    "Sanctus",
    "Tri-Cycles Race Bike",
    "Vindicator",
    "Wolfsbane",
    "Avarus",
    "Bati 801RR",
    "Cliffhanger",
    "Diabolus",
    "FCR 1000 Custom",
    "Hexer",
    "Shotaro",
    "Vortex",
    "BF-400",
    "Cruiser",
    "Diabolus Custom",
    "Future Shock Deathbike",
    "Sovereign",
    "Blazer",
    "Double-T",
    "Street Blazer",
    "Blazer Lifeguard",
    "Stryder",
    "BMX"
  ],
  not_sellable_cars: [
    "Annis Concept 2021",
    "Brabus Rocket G900",
    "Bravado Charger Daytona",
    "Enus EXP 10",
    "Genesis G90",
    "KMTA Optima",
    "Overflod Jesko 2020",
    "Pfister Cayenne",
    "Shelby Cobra Daytona",
    "Truffade Veyron",
    "Ubermacht M5 (F90)",
    "Vapid Focus RS",
    "Benefactor-MG G63 (6X6)",
    "Enus Wraith",
    "Grotti FXX-K Evo",
    "Karin Corolla AE",
    "Overflod CCX",
    "Pfister Panamera Turismo",
    "Skoda Octavia RS",
    "Truffade La Voiture Noire",
    "Ubermacht Z4 (E85)",
    "Vapid GT 2017",
    "Benefactor-Benz GLS 63",
    "Grotti Tributo (F8)",
    "Overflod One",
    "Pfister 911 Turbo 2021",
    "SSC Tuatara",
    "Truffade Bolide",
    "Ubermacht Vision",
    "Vapid Raptor F150",
    "Benefactor-Benz MG Visione",
    "Grotti Stradale (SF90)",
    "Overflod Gemera",
    "Pegassi Veneno (LP750)",
    "Truffade Divo",
    "Vapid Mustang 1965",
    "Benefactor-Benz Vision AVTR",
    "Grotti Superfast (F812)",
    "Overflod Regera",
    "Pegassi Centenario (LP770)",
    "Vapid Mustang MACH-E",
    "Benefactor-MG Project One",
    "Grotti Pista (F488)",
    "Obey TT",
    "Pegassi Terzo",
    "Benefactor-MG E63 (W213)",
    "Grotti Monza (SP2)",
    "Obey RS5 Coupe",
    "Pegassi Urus",
    "Benefactor-Maybach GLS600",
    "Gallivanter Evoque",
    "Obey RS E-Tron GT",
    "Pegassi Diablo (SV)",
    "Benefactor-MG GLE63 Coupe",
    "Obey E-Tron Sportback",
    "Pegassi Aventador (LP700)",
    "Benefactor-MG A45 (W176)",
    "Ocelot Vulcan",
    "Pegassi Alston (SC18)",
    "Benefactor-MG CLS53 (C257)",
    "Ocelot Evora",
    "Pegassi Reventon",
    "Benefactor-Benz GLC300",
    "Ocelot GranTurismo",
    "Pegassi Sian",
    "Benefactor-Benz 300 SL (W198)",
    "Pegassi Countach (LP400)",
    "Benefactor-Benz 190E (Evolution II)",
    "Pegassi Countach (LPI 800-4)",
    "Benefactor-Maybach S63 (W223)",
    "Pegassi SE (PJ1)",
    "Progen Elva",
    "Progen P1",
    "Progen 765 LT (Spider)"
  ],
  sellable_cars: [
    "Adder",
    "Baller",
    "Canis Grand Cherokee",
    "Declasse Corvette C7",
    "Elegy Retro Custom",
    "F620",
    "Gallivanter Defender",
    "Hermes",
    "Imorgon",
    "Jackal",
    "Kamacho",
    "Lampadati Giulia GTA",
    "Mamba",
    "Nebula Turbo",
    "Oracle",
    "Panto",
    "Raiden",
    "Sabre Turbo",
    "T-20",
    "Ubermacht 760 (LI)",
    "V-STR",
    "Warrener",
    "X80 Proto",
    "Yosemite",
    "Z-Type",
    "9F",
    "Alpha",
    "Baller LE LWB",
    "Calico GTF",
    "Declasse Tahoe",
    "Elegy RH8",
    "Faction",
    "Gallivanter Defender Halloween Edition",
    "Hotknife",
    "Impaler",
    "JB 700",
    "Khamelion",
    "Landstalker",
    "Massacro",
    "Neon",
    "Osiris",
    "Paragon R",
    "Rancher XL",
    "Sandking SWB",
    "Tailgater",
    "Ubermacht I8",
    "Vacca",
    "Warrener HKR",
    "XA-21",
    "Yosemite Rancher",
    "Zentorno",
    "9F Cabrio",
    "Annis ZR-350",
    "Baller SG",
    "Caracara 4x4",
    "Deveste Eight",
    "Ellie",
    "Felon",
    "Gallivanter Defender Christmas Edition",
    "Huntley S",
    "Infernus",
    "Jester",
    "Komoda",
    "Lynx",
    "Mammoth HUM EV",
    "Nero",
    "Obey A8",
    "Pariah",
    "Rapid GT",
    "Sandking XL",
    "Tailgater S",
    "Ubermacht M3 (G80)",
    "Vagner",
    "Washington",
    "XLS",
    "Zion",
    "Annis 350Z",
    "Banshee",
    "Carbonizzare",
    "Deviant",
    "Emperor",
    "Felon GT",
    "Gauntlet",
    "Infernus Classic",
    "Jester (Racecar)",
    "Krieger",
    "Monroe",
    "Nero Custom",
    "Obey R8",
    "Patriot",
    "Raptor",
    "SC-1",
    "Taipan",
    "Ubermacht M3 (E46)",
    "Vamos",
    "Windsor",
    "XLS (Armored)",
    "Zion Cabrio",
    "Annis Silvia (S15)",
    "Banshee 900R",
    "Casco",
    "Dilettante",
    "Emperor LX-570",
    "Feltzer",
    "Gauntlet Classic",
    "Ingot",
    "Jester Classic",
    "Karin Land Cruiser 200",
    "Moonbeam",
    "Nightshade",
    "Obey RS6",
    "Patriot Stretch",
    "Rat-Loader",
    "Schafter",
    "Tampa",
    "Ubermacht M4 (G82)",
    "Vectre",
    "Windsor Drop",
    "Annis Skyline GT-R (R34)",
    "Beater Emperor",
    "Cavalcade",
    "Dinka RT-3000",
    "Emperor RCF",
    "Flash GT",
    "Gauntlet Hellfire",
    "Issi",
    "Jester RR",
    "Karin Tundra 2021",
    "Monowheel",
    "Novak",
    "Obey RS7",
    "Pegassi Huayra BC",
    "Rat-Truck",
    "Schafter LWB",
    "Tempesta",
    "Ubermacht M4 (GTS)",
    "Velierer",
    "Zion Classic",
    "Annis GT-R I",
    "Beater Mariachi Tornado",
    "Cheburek",
    "Dinka NSX 2017",
    "Entity XF",
    "FMJ",
    "Gauntlet Redwood",
    "Itali GTB",
    "Journey",
    "Karin Supra A80",
    "Obey S8 (D4)",
    "Pegassi Performante (LP640)",
    "RE-7B",
    "Schafter LWB (Armored)",
    "Tezeract",
    "Ubermacht M5 (E34)",
    "Vigero",
    "Zorrusso",
    "Annis RX-7 (FD)",
    "Beater Surfer",
    "Cheetah",
    "Dominator",
    "Enus Cullinan",
    "FQ 2",
    "GB200",
    "Itali GTB Custom",
    "Jugular",
    "Karin Mark 2",
    "Ocelot Victor",
    "Penetrator",
    "Reaper",
    "Schafter V12",
    "Thrax",
    "Ubermacht M5 (E60)",
    "Virgo",
    "Annis RX-7 (Veilside Fortune)",
    "Beater Tornado",
    "Cheetah Classic",
    "Dominator ASP",
    "Enus Phantom",
    "Fugitive",
    "Glendale",
    "Itali GTO",
    "Ocelot F-Type R",
    "Penumbra",
    "Rebel",
    "Schlagen GT",
    "Tigon",
    "Ubermacht M5 (CS)",
    "Virgo Classic",
    "Annis WRX 2004",
    "Benefactor-MG C63 (W205)",
    "Chino",
    "Dominator GTT",
    "Enus Spectre",
    "Furore GT",
    "GP-1",
    "Obey A6",
    "Peyote Gasser",
    "Rebla GTS",
    "Schwarzer",
    "Torero",
    "Ubermacht M5 (CS) Halloween Edition",
    "Viseris",
    "Apocalypse Impaler",
    "Benefactor-MG C63 Coupe (W205)",
    "Clique",
    "Dominator GTX",
    "Enus Continental GT",
    "Fusilade",
    "Granger",
    "Obey Q8",
    "Pfister 811",
    "Regina",
    "Seminole",
    "Toros",
    "Ubermacht M8 (F91)",
    "Visione",
    "Apocalypse Imperator",
    "Benefactor-MG G63 (G770)",
    "Coil Cybertruck",
    "Dominator PiBwasser",
    "ETR-1",
    "Futo",
    "Growler",
    "Ocelot Vanquish Zagto SB",
    "Pfister Panamera",
    "Remus",
    "Sentinel Classic",
    "Tropos Rallye",
    "Ubermacht X5 (E70)",
    "Voltic",
    "Apocalypse Issi",
    "Benefactor-MG S63 (W222)",
    "Coil Model S",
    "Drift Yosemite",
    "Euros",
    "Futo GTX",
    "Grotti Italia (F458)",
    "Ocelot Eletre",
    "Pfister Taycan",
    "Revolter",
    "Sentinel XS",
    "Truffade Centodieci",
    "Ubermacht X5 (G05)",
    "Voodoo",
    "Apocalypse Slamvan",
    "Benefactor-MG VT Black Series",
    "Coil Model X",
    "Dubsta",
    "Exemplar",
    "Future Shock Issi",
    "GT 500",
    "Pfister 918 Spyder",
    "Rhapsody",
    "Serrano",
    "Tulip",
    "Ubermacht X6-M (E71)",
    "Voodoo Custom",
    "Ardent",
    "Benefactor-Benz 600SEL (W140)",
    "Coil Roadster",
    "Dubsta 6x6",
    "Pheonix",
    "Riata",
    "Seven-70",
    "Turismo Classic",
    "Ubermacht X7 (G07)",
    "Asbo",
    "Benefactor-Benz E420 (W210)",
    "Cognoscenti",
    "Dubsta SG",
    "Picador",
    "Rocoto",
    "Shelby GT500",
    "Turismo R",
    "Asea",
    "Benefactor-Benz Vito (V447)",
    "Cognoscenti 55",
    "Dukes",
    "Prairie",
    "Ruiner",
    "Slam Van",
    "Truffade Chiron",
    "Asterope",
    "Benefactor-Maybach Pullman",
    "Cognoscenti Cabrio",
    "Declasse Camaro 2020",
    "Premier",
    "Rumpo",
    "Slamvan Custom",
    "Tyrant",
    "Autarch",
    "Bestia GTS",
    "Comet",
    "Previon",
    "Ruston",
    "Specter",
    "Tyrus",
    "Albany Escalade",
    "BF Injection",
    "Comet S2",
    "Progen 675 LT",
    "Rusty Rebel",
    "Stafford",
    "Bison",
    "Comet SR",
    "Stallion",
    "Blade",
    "Contender",
    "Stinger",
    "Blista",
    "Coquette",
    "Stinger GT",
    "Blista Kanjo",
    "Coquette Blackfin",
    "Stirling GT",
    "Bodhi",
    "Coquette D10",
    "Streiter",
    "Brawler",
    "Couquette Classic",
    "Stretch",
    "Bravado Charger SRT",
    "Cyclone",
    "Sultan",
    "Bravado Charger 1969",
    "Cypher",
    "Bravado Challenger 2016",
    "Sultan Classic",
    "Bravado Ram 1500",
    "Sultan RS",
    "Bravado Viper 2008",
    "Sultan RS Classic",
    "Brioso R/A",
    "Super Diamond",
    "Buccaneer",
    "Surano",
    "Buffalo",
    "Surge",
    "Bullet",
    "Swinger",
    "Benefactor-MG GT",
    "Benefactor-MG SL65 (R230)",
    "Burgerfahrzeug Golf GTI Vision"
  ]
};
